Chatterzilla/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'chats/show'
  get 'users/new'
  mount ActionCable.server => '/cable'

  root   'sessions#new'
  #root 'home#index'
  #root to: "chats#show"
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :sessions
  resources :chats
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
end

Chatterzilla/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Chatterzilla/app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

Chatterzilla/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

Chatterzilla/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :login, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
end

Chatterzilla/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

Chatterzilla/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @messages = Message.all
  end
end

Chatterzilla/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])

    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])

    session[:conversations].delete(@conversation.id)

    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

Chatterzilla/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end
end

Chatterzilla/app/controllers/manda_controller.rb
class MandaController < ApplicationController
  def index
  end
end

Chatterzilla/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

Chatterzilla/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

Chatterzilla/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def index
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user).paginate(page: params[:page])

    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Chatterzilla!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:login, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

end

Chatterzilla/app/helpers/application_helper.rb
module ApplicationHelper
end

Chatterzilla/app/helpers/chats_helper.rb
module ChatsHelper
end

Chatterzilla/app/helpers/home_helper.rb
module HomeHelper
end

Chatterzilla/app/helpers/manda_helper.rb
module MandaHelper
end

Chatterzilla/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

Chatterzilla/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.login, class: "gravatar")
  end
end

Chatterzilla/app/views/chats/show.html.haml
%h1.title Bate Papo
#messages
  = render @messages
%form
  %input{"data-behavior" => "chat_speaker", :placeholder => " Diga alguma coisa :) ", :type => "text"}/
= link_to "Leave Chat Room", "../users#show" 

Chatterzilla/app/views/conversations/_conversation.html.haml
%li
  .panel.panel-default{"data-conversation-id" => "#{conversation.id}"}
    .panel-heading
      = link_to conversation.opposed_user(user).email, '', class: 'toggle-window'
      = link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post
    .panel-body{style: "display: none;"}
      .messages-list
        %ul
          = render 'conversations/conversation_content', messages: conversation.messages, user: user
      = form_for [conversation, conversation.messages.new], remote: true do |f|
        = f.hidden_field :user_id, value: user.id
        = f.text_area :body, class: "form-control"
        = f.submit "Send", class: "btn btn-success"

Chatterzilla/app/views/conversations/_conversation_content.html.haml
- messages.each do |message|
  = render message, user: user

Chatterzilla/app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

Chatterzilla/app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

Chatterzilla/app/views/home/index.html.haml
.row
  .col-md-9
    %ul#conversations-list
      - @conversations.each do |conversation|
        = render 'conversations/conversation', conversation: conversation, user: current_user
  .col-md-3
    .panel.panel-primary
      .panel-heading
        %h3.panel-title User list
      .panel-body
        %ul
          - @users.each do |user|
            %li= user.email

Chatterzilla/app/views/layouts/_nav.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    - if logged_in?
      = link_to "Chatterzilla", users_path, id: "logo"
    - else
      = link_to "Chatterzilla", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= link_to "Home", users_path
        - else
          %li= link_to "Home", root_path          
        - if logged_in?
          %li= link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path

Chatterzilla/app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatterzilla
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    =render 'layouts/nav'
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
    = yield

Chatterzilla/app/views/manda/index.html.haml
%h1 Manda#index
%p Eita que agora a gente esta progredindo!

Chatterzilla/app/views/messages/_message.html.haml
%li
	%div{class: "#{user.id == message.user_id ? 'message-sent' : 'message-received'}"}
		= message.body

Chatterzilla/app/views/messages/create.js.erb
var conversation = $('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.messages-list').find('ul').append("<%= j(render 'messages/message', message: @message, user: current_user) %>");
conversation.find('textarea').val('');

Chatterzilla/app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

Chatterzilla/app/views/users/_form.html.haml
= form_for(@user) do |f|
  = render 'shared/error_messages', object: @user
  = f.label :login
  = f.text_field :login, class: 'form-control'
  = f.label :email
  = f.email_field :email, class: 'form-control'
  = f.label :password
  = f.password_field :password, class: 'form-control'
  = f.label :password_confirmation
  = f.password_field :password_confirmation, class: 'form-control'
  = f.submit yield(:button_text), class: "btn btn-primary"

Chatterzilla/app/views/users/destroy.html.haml
%h1  Pronto!
%p
O Usuario selecionado foi apagado!
%p
= link_to  "Voltar", new_user_path

Chatterzilla/app/views/users/edit.html.haml
- provide(:title, 'Edit user')
- provide(:button_text, 'Save changes')
%body
  .container
    %h1 Update your profile
    .row
      .col-md-6.col-md-offset-3
        = render 'form'
        .gravatar_edit
          = gravatar_for @user
          %a{:href => "http://gravatar.com/emails", :target => "_blank"} Change

Chatterzilla/app/views/users/index.html.haml
- provide(:title, 'All users')
%body
  .containerusers
    .row
      .col-xs-6.align-self-center
        %h1 All users  
        .panel.panel-primary
          .panel-body
            = will_paginate
            %ul.users
              - @users.each do |user|
                %li
                  = gravatar_for user, size: 50
                  = link_to "Open chat with " + user.login, conversations_path(user_id: user), remote: true, method: :post 
                  %br/ 
                  = link_to "Profile", user 
            = will_paginate
      .col-xs-9.align-self-start
        %h1 My conversations
        %ul.users#conversations-list
          - @conversations.each do |conversation|
            = render 'conversations/conversation', conversation: conversation, user: current_user

Chatterzilla/app/views/users/new.html.haml
- provide(:title, 'Sign up')
- provide(:button_text, 'Create my account')
%body
  .container
    %h1 Sign up
    .row
      .col-md-6.col-md-offset-3
        = render 'form'

Chatterzilla/app/views/users/show.html.haml
%body
  .container
    .row.align-items-center
      .col.align-self-center
        %h1 User profile
    .row
      .col-xs-6.align-self-center
        %p
          = @user.login
        %p 
          = @user.email
      .col-xs-6.align-self-center
        = gravatar_for @user
    = link_to "Go to Chat Room!", "../chats/show"  